# Calculo entre matrices y vectores usando numpy

In [1]:
!python --version

Python 3.10.9


Estamos ejecutando en python version 3.10.9

### Importar librerias

In [2]:
import numpy

### Crear arreglos sin numpy

In [4]:
A = [[-5,2],[3,-1],[1,0]]
print(A)

[[-5, 2], [3, -1], [1, 0]]


In [5]:
B = [[1,2],[0,5],[3,-1]]
print(B)

[[1, 2], [0, 5], [3, -1]]


In [7]:
Resultado = A+B
print(Resultado) # Sin usar numpy (concatenacion de arreglos)

[[-5, 2], [3, -1], [1, 0], [1, 2], [0, 5], [3, -1]]


### Convertir arreglos a matrices con numpy

In [8]:
A = numpy.array(A) # Ahora A es una matriz de numpy
print(A)

[[-5  2]
 [ 3 -1]
 [ 1  0]]


In [9]:
B=numpy.array(B)
print(B)

[[ 1  2]
 [ 0  5]
 [ 3 -1]]


### Suma y resta de matrices

In [10]:
Resultado = A+B
print(Resultado)

[[-4  4]
 [ 3  4]
 [ 4 -1]]


In [11]:
print(A+B)

[[-4  4]
 [ 3  4]
 [ 4 -1]]


In [13]:
print('Este es el resultado de A-B=')
print(A-B)

Este es el resultado de A-B=
[[-6  0]
 [ 3 -6]
 [-2  1]]


### Escalar por una matriz

In [14]:
x = -2
print(x*A)

[[10 -4]
 [-6  2]
 [-2  0]]


### Multiplicacion elemento a elemento

In [15]:
print(A, '\n\n', B)

[[-5  2]
 [ 3 -1]
 [ 1  0]] 

 [[ 1  2]
 [ 0  5]
 [ 3 -1]]


In [16]:
print(A*B) # Multiplica elemento a elemento, PEROOOOO, no es una multiplicacion entre matrices.

[[-5  4]
 [ 0 -5]
 [ 3  0]]


In [19]:
# C = numpy.array([[2,-1,3],[1,0,-2]])
# print(C)
import numpy as np
C = np.array([[2,-1,3],[1,0,-2]])
print(C)


[[ 2 -1  3]
 [ 1  0 -2]]


In [20]:
print(C*A)

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [21]:
print('Dimensiones de C:', np.shape(C))
print('Dimensiones de A:', np.shape(A))


Dimensiones de C: (2, 3)
Dimensiones de A: (3, 2)


### Multiplicacion matricial

In [22]:
Resultado = np.dot(C, A) #Esta SI es una multplicacion matricial
print(Resultado)

[[-10   5]
 [ -7   2]]


In [23]:
print(np.dot(A,C))

[[ -8   5 -19]
 [  5  -3  11]
 [  2  -1   3]]


In [24]:
print(np.transpose(C))
print()
print(np.transpose(A))

[[ 2  1]
 [-1  0]
 [ 3 -2]]

[[-5  3  1]
 [ 2 -1  0]]


In [25]:
(2)*(-5)+(1)*(2)

-8

### Declaracion de vectores con complejos

In [27]:
# z1 = np.array([-j, 1+j, 0, 1+2j]) # ! Error: j siempre debe tener un coeficiente numerico.
z1 = np.array([-1j, 1+1j, 0, 1+2j])
print(z1)

[-0.-1.j  1.+1.j  0.+0.j  1.+2.j]


-0.-1.j = -0-1j = -j

0.+0.j = 0+0j = 0

In [28]:
z2 = np.array([0, 1j, 1-2j, complex(3, 1)])
print(z2)

[0.+0.j 0.+1.j 1.-2.j 3.+1.j]


### Suma entre vectores

In [29]:
print(z1+z2)

[0.-1.j 1.+2.j 1.-2.j 4.+3.j]


### Producto punto entre vectores

In [30]:
print(np.dot(z1,z2))

8j


### Producto tensorial

In [31]:
print(np.tensordot(z1,z2,axes=0)) # axes=0 es el producto tensorial

[[ 0.+0.j  1.+0.j -2.-1.j  1.-3.j]
 [ 0.+0.j -1.+1.j  3.-1.j  2.+4.j]
 [ 0.+0.j  0.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j -2.+1.j  5.+0.j  1.+7.j]]


In [32]:
print(np.shape(z1))
print(np.shape(z2))

(4,)
(4,)


In [33]:
z1_2D = np.atleast_2d(z1)
print(z1)
print()
print(z1_2D) # Vector fila

[-0.-1.j  1.+1.j  0.+0.j  1.+2.j]

[[-0.-1.j  1.+1.j  0.+0.j  1.+2.j]]


In [34]:
z1T = np.transpose(z1_2D)
print(z1T) # Vector columna

[[-0.-1.j]
 [ 1.+1.j]
 [ 0.+0.j]
 [ 1.+2.j]]


In [35]:
z2_2D = np.atleast_2d(z2)
z2T = z2_2D.T # Es igual a np.transpose(z2_2D)
print(z2T)

[[0.+0.j]
 [0.+1.j]
 [1.-2.j]
 [3.+1.j]]


In [36]:
print(np.tensordot(z1T, z2T, axes=0))

[[[[ 0.+0.j]
   [ 1.+0.j]
   [-2.-1.j]
   [ 1.-3.j]]]


 [[[ 0.+0.j]
   [-1.+1.j]
   [ 3.-1.j]
   [ 2.+4.j]]]


 [[[ 0.+0.j]
   [ 0.+0.j]
   [ 0.+0.j]
   [ 0.+0.j]]]


 [[[ 0.+0.j]
   [-2.+1.j]
   [ 5.+0.j]
   [ 1.+7.j]]]]


### Ejemplo de muchas instrucciones en una sola linea de codigo

In [39]:
# z2 = np.array([0,1j,-2j,3+1j])
# z2T = np.atleast_2d(z2).T
# print(np.tensordot(z1T, z2T, axes=0))
print(np.tensordot(z1T, np.atleast_2d(np.array([0,1j,-2j,3+1j])).T, axes=0))


[[[[ 0.+0.j]
   [ 1.+0.j]
   [-2.+0.j]
   [ 1.-3.j]]]


 [[[ 0.+0.j]
   [-1.+1.j]
   [ 2.-2.j]
   [ 2.+4.j]]]


 [[[ 0.+0.j]
   [ 0.+0.j]
   [ 0.+0.j]
   [ 0.+0.j]]]


 [[[ 0.+0.j]
   [-2.+1.j]
   [ 4.-2.j]
   [ 1.+7.j]]]]
